export const translations = {
    ru: {
        // Nav
        main: "Главное", services: "Услуги", prices: "Цены", doctors: "Врачи", certificates: "Сертификаты",
        // Hero
        hero_badge: "Высокие технологии цифровой стоматологии",
        hero_title: "Безупречная эстетика и здоровье ваших зубов в Оше.",
        hero_text: "Инновационный подход медицинского центра «Галерея Улыбок». Мы объединили опыт ведущих специалистов южной столицы и передовое оборудование.",
        btn_book: "Записаться на прием", btn_services: "Наши услуги",
        stat_patients: "счастливые пациенты", stat_experience: "опыта на рынке", stat_doctors: "высококлассных врачей", stat_tech: "Современные технологии",
        // Sections
        services_title: "Наши услуги", services_sub: "Современные методики лечения. Нажмите на нужную услугу, и она подставится в форму записи.",
        price_title: "Цены на услуги", price_sub: "Честное и прозрачное ценообразование. Цены указаны в сомах (KGS).",
        doctors_title: "Наши врачи", doctors_sub: "Команда сертифицированных профессионалов клиники «Галерея Улыбок».",
        contact_title: "Онлайн запись", contact_sub: "Выберите желаемую услугу, врача и свободное время.",
        // Form placeholders & labels
        label_name: "Имя", label_surname: "Фамилия", label_phone: "Номер телефона", 
        label_service: "Выбрать услугу", label_doctor: "Выбрать врача", label_date: "День", 
        label_time: "Выбрать время", label_comment: "Комментарий", btn_submit: "Записаться на прием",
        ph_name: "Пример: Айбек", ph_surname: "Пример: Кадыров", ph_comment: "Опишите ваши симптомы...",
        // Dynamic Services
        srv1_title: "Терапия", srv1_desc: "Лечение кариеса, пульпита и периодонтита любой сложности.",
        srv2_title: "Ортопедия", srv2_desc: "Установка коронок, мостов и современных виниров.",
        srv3_title: "Хирургия", srv3_desc: "Безболезненное удаление зубов и имплантация.",
        srv4_title: "Ортодонтия", srv4_desc: "Исправление прикуса брекетами и элайнерами.",
        srv5_title: "Отбеливание", srv5_desc: "Профессиональное и безопасное отбеливание зубов.",
        srv6_title: "Детская стоматология", srv6_desc: "Особый подход к лечению зубов у детей.",
        // Dynamic Prices
        pr1_name: "Первичная консультация", pr2_name: "Лечение кариеса", pr3_name: "Установка импланта", pr4_name: "Металлокерамическая коронка", pr5_name: "Профессиональная чистка",
        // Dynamic Doctors
        doc1_name: "Азиз Каримов", doc1_spec: "Главный врач, Стоматолог-ортопед",
        doc2_name: "Мадина Алиева", doc2_spec: "Стоматолог-терапевт, Эндодонтист",
        doc3_name: "Руслан Бакиров", doc3_spec: "Челюстно-лицевой хирург, Имплантолог"
    },
    uz: {
        main: "Asosiy", services: "Xizmatlar", prices: "Narxlar", doctors: "Shifokorlar", certificates: "Sertifikatlar",
        hero_badge: "Raqamli stomatologiyaning yuqori texnologiyalari",
        hero_title: "O'sh shahrida tishlaringizning mukammal estetikasi va salomatligi.",
        hero_text: "«Galereya Ulibok» tibbiyot markazining innovatsion yondashuvi. Biz janubiy poytaxtning yetakchi mutaxassislari tajribasini va ilg'or uskunalarni birlashtirdik.",
        btn_book: "Qabulga yozilish", btn_services: "Bizning xizmatlar",
        stat_patients: "baxtli bemorlar", stat_experience: "yillik tajriba", stat_doctors: "malakali shifokorlar", stat_tech: "Zamonaviy texnologiyalar",
        services_title: "Bizning xizmatlar", services_sub: "Zamonaviy davolash usullari. Kerakli xizmatni bossangiz, u avtomatik ravishda yozilish formasiga qo'shiladi.",
        price_title: "Xizmat narxlari", price_sub: "Yashirin to'lovlarsiz halol narxlar. Narxlar somda (KGS) ko'rsatilgan.",
        doctors_title: "Bizning shifokorlar", doctors_sub: "«Galereya Ulibok» klinikasining sertifikatlangan professionallar jamoasi.",
        contact_title: "Onlayn yozilish", contact_sub: "O'zingizga kerakli xizmatni, shifokorni va bo'sh vaqtni tanlang.",
        label_name: "Ism", label_surname: "Familiya", label_phone: "Telefon raqam", 
        label_service: "Xizmatni tanlang", label_doctor: "Shifokorni tanlang", label_date: "Kun", 
        label_time: "Vaqtni tanlang", label_comment: "Izoh", btn_submit: "Qabulga yozilish",
        ph_name: "Masalan: Aybek", ph_surname: "Masalan: Qodirov", ph_comment: "Shikoyatlaringizni yozing...",
        srv1_title: "Terapiya", srv1_desc: "Karies, pulpit va periodontitni og'riqsiz davolash.",
        srv2_title: "Ortopediya", srv2_desc: "Koronka, ko'prik va zamonaviy vinirlar o'rnatish.",
        srv3_title: "Xirurgiya", srv3_desc: "Tishlarni og'riqsiz yulish va implantatsiya.",
        srv4_title: "Ortodontiya", srv4_desc: "Breket va elaynerlar yordamida tishlamni to'g'rilash.",
        srv5_title: "Oqartirish", srv5_desc: "Tishlarni professional va xavfsiz oqartirish.",
        srv6_title: "Bolalar stomatologiyasi", srv6_desc: "Bolalar tishlarini davolashda maxsus yondashuv.",
        pr1_name: "Birlamchi konsultatsiya", pr2_name: "Kariesni davolash", pr3_name: "Implant o'rnatish", pr4_name: "Metallokeramika koronkasi", pr5_name: "Professional tozalash",
        doc1_name: "Aziz Karimov", doc1_spec: "Bosh shifokor, Stomatolog-ortoped",
        doc2_name: "Madina Aliyeva", doc2_spec: "Stomatolog-terapevt, Endodontist",
        doc3_name: "Ruslan Bakirov", doc3_spec: "Yuz-jag' xirurgi, Implantolog"
    },
    en: {
        main: "Home", services: "Services", prices: "Prices", doctors: "Doctors", certificates: "Certificates",
        hero_badge: "High-tech digital dentistry",
        hero_title: "Flawless aesthetics and health of your teeth in Osh.",
        hero_text: "Innovative approach of 'Gallery of Smiles'. We combined the experience of leading specialists and advanced European equipment.",
        btn_book: "Book an Appointment", btn_services: "Our Services",
        stat_patients: "happy patients", stat_experience: "years of experience", stat_doctors: "top-class doctors", stat_tech: "Modern technologies",
        services_title: "Our Services", services_sub: "Modern treatment methods. Click on a service to add it to the booking form.",
        price_title: "Prices", price_sub: "Honest and transparent pricing. Prices are in soms (KGS).",
        doctors_title: "Our Doctors", doctors_sub: "Team of certified professionals at 'Gallery of Smiles'.",
        contact_title: "Online Booking", contact_sub: "Select your desired service, doctor, and available time.",
        label_name: "Name", label_surname: "Surname", label_phone: "Phone Number", 
        label_service: "Select Service", label_doctor: "Select Doctor", label_date: "Date", 
        label_time: "Select Time", label_comment: "Comment", btn_submit: "Book Appointment",
        ph_name: "Example: John", ph_surname: "Example: Doe", ph_comment: "Describe your symptoms...",
        srv1_title: "Therapy", srv1_desc: "Treatment of caries, pulpitis, and periodontitis.",
        srv2_title: "Orthopedics", srv2_desc: "Installation of crowns, bridges, and veneers.",
        srv3_title: "Surgery", srv3_desc: "Painless tooth extraction and implantation.",
        srv4_title: "Orthodontics", srv4_desc: "Bite correction with braces and aligners.",
        srv5_title: "Whitening", srv5_desc: "Professional and safe teeth whitening.",
        srv6_title: "Pediatric Dentistry", srv6_desc: "Special approach to treating children's teeth.",
        pr1_name: "Initial consultation", pr2_name: "Caries treatment", pr3_name: "Implant placement", pr4_name: "Metal-ceramic crown", pr5_name: "Professional cleaning",
        doc1_name: "Aziz Karimov", doc1_spec: "Chief Physician, Orthopedist",
        doc2_name: "Madina Alieva", doc2_spec: "Therapist, Endodontist",
        doc3_name: "Ruslan Bakirov", doc3_spec: "Maxillofacial Surgeon, Implantologist"
    }
};
