const translations = {
    uz: {
        main: "Asosiy", services: "Xizmatlar", prices: "Narxlar", doctors: "Shifokorlar", certificates: "Sertifikatlar",
        hero_badge: "Premium raqamli stomatologiya",
        hero_title: "O'shda mukammal tabassum va tishlar salomatligi.",
        hero_text: "G-Smile tibbiyot markazining innovatsion yondashuvi. Biz janubiy poytaxtning yetakchi mutaxassislari tajribasi va Yevropaning ilg'or uskunalarini birlashtirdik.",
        btn_book: "Qabulga yozilish", btn_services: "Xizmatlarimiz",
        stat_patients: "Baxtli bemorlar", stat_experience: "Yillik tajriba", stat_doctors: "Yuqori malakali shifokorlar", stat_tech: "3D Texnologiyalar",
        services_title: "Bizning xizmatlar",
        services_sub: "Zamonaviy davolash usullari. Kerakli xizmatni bosing, u avtomatik ravishda yozilish formasiga qo'shiladi.",
        service_click: "Yozilish uchun bosing",
        price_title: "Narxlar", price_sub: "Yashirin to'lovlarsiz shaffof narxlar. Narxlar so'mda (KGS) ko'rsatilgan.",
        why_title: "Nima uchun bizni tanlashadi", why_sub: "Tish davolash faqat qulaylik bilan bog'liq bo'lishi uchun barcha sharoitlarni yaratdik.",
        why_tech_title: "Innovatsion texnologiyalar", why_tech_text: "Mikroskop ostida davolash, raqamli diagnostika.",
        why_doc_title: "Tajribali shifokorlar", why_doc_text: "Xalqaro stajirovkalardan o'tgan mutaxassislar.",
        why_ind_title: "Individual yondashuv", why_ind_text: "Har bir bemor uchun shaxsiy davolash rejasi.",
        why_loc_title: "Qulay joylashuv", why_loc_text: "O'sh sh., Asqar Shakirov 271. Qulay avtoturargoh.",
        why_sched_title: "Qulay ish vaqti", why_sched_text: "Dam olish kunlarisiz 8:00 dan 21:00 gacha qabul.",
        doctors_title: "Bizning mutaxassislar", doctors_sub: "G-Smile klinikasining sertifikatlangan jamoasi.",
        cert_title: "Sertifikatlar va litsenziyalar", cert_sub: "Klinikamiz xalqaro standartlarga to'liq javob beradi.",
        reviews_title: "Bemorlarimiz fikri", reviews_sub: "Bizning eng katta yutug'imiz — sizning sog'lom tabassumingiz.",
        review_1_name: "Aziza T.", review_1_text: "Juda ajoyib klinika! Shifokorlar o'z ishining ustasi. Tishimni umuman og'riqsiz davolashdi. Barchaga tavsiya qilaman!",
        review_2_name: "Bektur M.", review_2_text: "Implantatsiya bo'yicha murojaat qilgandim. Arapov Islambek juda professional ishladi. Natijadan juda xursandman.",
        review_3_name: "Madina K.", review_3_text: "Bolalar stomatologi Nazima opaga katta rahmat. Farzandim endi tish shifokoriga qo'rqmasdan boradigan bo'ldi.",
        contact_title: "Onlayn yozilish", contact_sub: "Qulay vaqtni tanlang, tizim band vaqtlarni avtomatik yashiradi.",
        label_surname: "Familiya", label_name: "Ism", label_phone: "Telefon", label_service: "Xizmat", label_doctor: "Shifokor", label_date: "Sana", label_time: "Vaqt", label_comment: "Izoh",
        btn_submit: "Qabulga yozilish",
        placeholder_surname: "Qodirov", placeholder_name: "Alisher", placeholder_phone: "557 702 270", placeholder_comment: "Semptomlar yoki tilaklar...",
        select_service: "-- Xizmatni tanlang --", select_doctor: "-- Shifokorni tanlang --", select_time_available: "-- Vaqtni tanlang --",
        service_selected: "✅ \"{service}\" tanlandi!", fill_all_fields: "Barcha maydonlarni to'ldiring!", phone_9_digits: "Raqam 9 ta sondan iborat bo'lishi kerak!",
        booking_success: "✅ {name}, siz {doctor} ga {time} da yozildingiz!", booking_error: "❌ Xatolik. Qayta urinib ko'ring.", sending: "Yuborilmoqda...",
        service_consultation: "Maslahat va ko'rik", service_extraction: "Tish chiqarish (oddiy)", service_caries: "Kariesni davolash", service_pulpitis: "Pulpitni davolash", service_cleaning: "Ultratovush tozalash", service_whitening: "Zoom oqartirish", service_crown: "Metall-keramika", service_zirconia: "Tsirkon koronkasi", service_veneer: "Keramik vinir", service_implant: "Dental implantatsiya", service_braces: "Breket o'rnatish", service_gum: "Milk kasalliklarini davolash", service_fissure: "Fessuralarni germetiklash", service_xray: "3D surat", service_nightguard: "Tungi kapna", service_wisdom: "Donolik tishini chiqarish", service_aligners: "Elaynerlar",
        price_consultation: "500 som", price_extraction: "599 som dan", price_caries: "2000 som", price_pulpitis: "3200 som", price_cleaning: "2500 som", price_whitening: "12000 som", price_crown: "4500 som", price_zirconia: "9500 som", price_veneer: "15000 som", price_implant: "22000 som", price_braces: "25000 som", price_gum: "1800 som", price_fissure: "1200 som", price_xray: "350 som", price_nightguard: "3800 som", price_wisdom: "4500 som dan", price_aligners: "70000 som dan",
        doctor_arapov: "Arapov Islambek", doctor_arapov_role: "Bosh shifokor, Implantolog", doctor_arapov_exp: "10 yillik tajriba", doctor_arapov_edu: "QDTU ni tamomlagan. Yuz-jag' jarrohligi ordinaturasi. Straumann va Osstem tizimlari bo'yicha mutaxassis (Janubiy Koreya).",
        doctor_ermatov: "Ermatov Baqtibek", doctor_ermatov_role: "Stomatolog-Ortoped", doctor_ermatov_exp: "8 yillik tajriba", doctor_ermatov_edu: "OshDU diplomi. Mikroprotezlash, E-Max metall bo'lmagan koronkalar va CAD/CAM vinirlarga ixtisoslashgan.",
        doctor_salieva: "Saliyeva Alina", doctor_salieva_role: "Stomatolog-Terapevt", doctor_salieva_exp: "7 yillik tajriba", doctor_salieva_edu: "QDU ni tamomlagan. Badiiy restavratsiya va mikroskop ostida murakkab ildiz kanallarini davolash.",
        doctor_kasymov: "Kasimov Nursultan", doctor_kasymov_role: "Ortodont", doctor_kasymov_exp: "6 yillik tajriba", doctor_kasymov_edu: "QDTU. Damon breket tizimlari va elaynerlar yordamida tishlarning noto'g'ri joylashuvini davolash.",
        doctor_mamatova: "Mamatova Nazima", doctor_mamatova_role: "Bolalar stomatologi", doctor_mamatova_exp: "5 yillik tajriba", doctor_mamatova_edu: "OshDU. Bolalar stomatologiyasi kurslari. Sut tishlarini o'yin shaklida og'riqsiz davolash.",
        doctor_abdullaev: "Abdullaev Rustam", doctor_abdullaev_role: "Umumiy amaliyot, gigienist", doctor_abdullaev_exp: "5 yillik tajriba", doctor_abdullaev_edu: "OshDU. Profilaktik stomatologiya, Zoom 4 oqartirish va parodont kasalliklarini davolash.",
        footer_desc: "Qirg'izistondagi yangi avlod stomatologiya klinikasi.", footer_contacts: "Kontaktlar", footer_address: "O'sh sh., Asqar Shakirov ko'chasi, 271", footer_hours: "Ish jadvali", footer_days: "Dushanba — Shanba", footer_sunday: "Yakshanba — Dam olish kuni", footer_copyright: "«G-Smile» stomatologiyasi. Barcha huquqlar himoyalangan."
    },
    en: {
        main: "Home", services: "Services", prices: "Prices", doctors: "Doctors", certificates: "Certificates",
        hero_badge: "Premium Digital Dentistry",
        hero_title: "Flawless smiles and dental health in Osh.",
        hero_text: "The innovative approach of the G-Smile medical center. Combining top specialists' expertise with advanced European equipment.",
        btn_book: "Book Appointment", btn_services: "Our Services",
        stat_patients: "Happy Patients", stat_experience: "Years Experience", stat_doctors: "Expert Doctors", stat_tech: "3D Technology",
        services_title: "Our Services",
        services_sub: "Modern treatments. Click a service to auto-fill the booking form below.",
        service_click: "Click to book",
        price_title: "Transparent Prices", price_sub: "No hidden fees. All prices are in KGS.",
        why_title: "Why Choose Us", why_sub: "We provide maximum comfort and world-class dental care.",
        why_tech_title: "Modern Tech", why_tech_text: "Microscope treatments and 3D diagnostics.",
        why_doc_title: "Expert Doctors", why_doc_text: "Internationally trained specialists.",
        why_ind_title: "Personalized Care", why_ind_text: "Individual treatment plans for everyone.",
        why_loc_title: "Great Location", why_loc_text: "Osh, Askar Shakirov 271. Easy parking.",
        why_sched_title: "Flexible Hours", why_sched_text: "Open 8:00 AM to 9:00 PM.",
        doctors_title: "Our Specialists", doctors_sub: "The certified team of G-Smile clinic.",
        cert_title: "Licenses & Facilities", cert_sub: "Meeting strict international medical standards.",
        reviews_title: "Patient Reviews", reviews_sub: "Your healthy smile is our biggest achievement.",
        review_1_name: "Anna S.", review_1_text: "Amazing clinic! The doctors are true professionals. Painless treatment, highly recommend!",
        review_2_name: "Max B.", review_2_text: "Got my implants done by Dr. Arapov. Smooth process and perfect results.",
        review_3_name: "Elena K.", review_3_text: "Dr. Nazima is wonderful with kids. My daughter is no longer afraid of the dentist.",
        contact_title: "Book Online", contact_sub: "Select service, doctor, and an available time slot.",
        label_surname: "Surname", label_name: "Name", label_phone: "Phone", label_service: "Service", label_doctor: "Doctor", label_date: "Date", label_time: "Time", label_comment: "Notes",
        btn_submit: "Confirm Booking",
        placeholder_surname: "Smith", placeholder_name: "John", placeholder_phone: "557 702 270", placeholder_comment: "Any symptoms...",
        select_service: "-- Select Service --", select_doctor: "-- Select Doctor --", select_time_available: "-- Select Time --",
        service_selected: "✅ \"{service}\" selected!", fill_all_fields: "Fill all required fields!", phone_9_digits: "Phone needs 9 digits!",
        booking_success: "✅ {name}, booked with {doctor} at {time}!", booking_error: "❌ Error. Try again.", sending: "Sending...",
        service_consultation: "Consultation", service_extraction: "Tooth extraction", service_caries: "Caries treatment", service_pulpitis: "Pulpitis treatment", service_cleaning: "Ultrasonic cleaning", service_whitening: "Zoom whitening", service_crown: "Metal-ceramic crown", service_zirconia: "Zirconia crown", service_veneer: "Ceramic veneer", service_implant: "Dental implant", service_braces: "Braces", service_gum: "Gum treatment", service_fissure: "Fissure sealing", service_xray: "3D X-ray", service_nightguard: "Night guard", service_wisdom: "Wisdom tooth removal", service_aligners: "Aligners",
        price_consultation: "500 som", price_extraction: "from 599 som", price_caries: "2000 som", price_pulpitis: "3200 som", price_cleaning: "2500 som", price_whitening: "12000 som", price_crown: "4500 som", price_zirconia: "9500 som", price_veneer: "15000 som", price_implant: "22000 som", price_braces: "25000 som", price_gum: "1800 som", price_fissure: "1200 som", price_xray: "350 som", price_nightguard: "3800 som", price_wisdom: "from 4500 som", price_aligners: "from 70000 som",
        doctor_arapov: "Arapov Islambek", doctor_arapov_role: "Chief Surgeon", doctor_arapov_exp: "10 years exp", doctor_arapov_edu: "Specialist in bone grafting & implants (Straumann/Osstem).",
        doctor_ermatov: "Ermatov Baktybek", doctor_ermatov_role: "Orthopedist", doctor_ermatov_exp: "8 years exp", doctor_ermatov_edu: "Specializes in CAD/CAM veneers and E-Max crowns.",
        doctor_salieva: "Salieva Alina", doctor_salieva_role: "Endodontist", doctor_salieva_exp: "7 years exp", doctor_salieva_edu: "Expert in artistic restorations and microscope endodontics.",
        doctor_kasymov: "Kasymov Nursultan", doctor_kasymov_role: "Orthodontist", doctor_kasymov_exp: "6 years exp", doctor_kasymov_edu: "Specialist in Damon braces and clear aligners.",
        doctor_mamatova: "Mamatova Nazima", doctor_mamatova_role: "Pediatric Dentist", doctor_mamatova_exp: "5 years exp", doctor_mamatova_edu: "Painless pediatric treatments through interactive play.",
        doctor_abdullaev: "Abdullaev Rustam", doctor_abdullaev_role: "Hygienist", doctor_abdullaev_exp: "5 years exp", doctor_abdullaev_edu: "Focuses on preventive care and Zoom 4 whitening.",
        footer_desc: "Next-gen dental clinic in Kyrgyzstan.", footer_contacts: "Contacts", footer_address: "Osh, Askar Shakirov 271", footer_hours: "Hours", footer_days: "Mon — Sat", footer_sunday: "Sunday — Closed", footer_copyright: "G-Smile Dentistry. All rights reserved."
    },
    ru: {
        main: "Главная", services: "Услуги", prices: "Цены", doctors: "Врачи", certificates: "Сертификаты",
        hero_badge: "Премиальная цифровая стоматология",
        hero_title: "Безупречная эстетика и здоровье ваших зубов в Оше.",
        hero_text: "Инновационный подход центра «Галерея Улыбок». Мы объединили опыт ведущих специалистов и передовое европейское оборудование для безболезненного лечения.",
        btn_book: "Записаться на прием", btn_services: "Наши услуги",
        stat_patients: "Счастливых пациентов", stat_experience: "Лет опыта", stat_doctors: "Врачей-экспертов", stat_tech: "3D Технологии",
        services_title: "Наши услуги",
        services_sub: "Современные методики лечения. Нажмите на нужную услугу, и она автоматически подставится в форму записи.",
        service_click: "Нажмите для записи",
        price_title: "Прозрачные цены", price_sub: "Честное ценообразование без скрытых переплат. Цены в сомах (KGS).",
        why_title: "Почему выбирают нас", why_sub: "Идеальные условия для того, чтобы лечение ассоциировалось только с комфортом.",
        why_tech_title: "Современные технологии", why_tech_text: "Лечение под микроскопом, 3D-моделирование.",
        why_doc_title: "Опытные врачи", why_doc_text: "Регулярное международное обучение.",
        why_ind_title: "Индивидуальный подход", why_ind_text: "Персональный пошаговый план лечения.",
        why_loc_title: "Удобное местоположение", why_loc_text: "Ош, ул. Аскара Шакирова, 271. Парковка.",
        why_sched_title: "Удобный график", why_sched_text: "Работаем с 8:00 до 21:00. Вы успеете после работы.",
        doctors_title: "Наши специалисты", doctors_sub: "Команда сертифицированных профессионалов.",
        cert_title: "Сертификаты и лицензии", cert_sub: "Оборудование отвечает строгим международным стандартам.",
        reviews_title: "Отзывы пациентов", reviews_sub: "Ваша здоровая улыбка — наше главное достижение.",
        review_1_name: "Азиза Т.", review_1_text: "Прекрасная клиника! Врачи — настоящие профессионалы. Вылечили зуб совершенно без боли. Рекомендую!",
        review_2_name: "Бектур М.", review_2_text: "Ставил импланты у Арапова Исламбека. Все прошло идеально, результатом очень доволен.",
        review_3_name: "Мадина К.", review_3_text: "Огромное спасибо детскому стоматологу Назиме. Мой ребенок больше не боится лечить зубы.",
        contact_title: "Онлайн запись", contact_sub: "Выберите услугу, врача и свободное время. Система скроет занятые часы.",
        label_surname: "Фамилия", label_name: "Имя", label_phone: "Телефон", label_service: "Услуга", label_doctor: "Врач", label_date: "Дата", label_time: "Время", label_comment: "Комментарий",
        btn_submit: "Подтвердить запись",
        placeholder_surname: "Кадыров", placeholder_name: "Айбек", placeholder_phone: "557 702 270", placeholder_comment: "Опишите симптомы...",
        select_service: "-- Выберите услугу --", select_doctor: "-- Выберите врача --", select_time_available: "-- Выберите время --",
        service_selected: "✅ Услуга \"{service}\" выбрана!", fill_all_fields: "Заполните все обязательные поля!", phone_9_digits: "Номер должен содержать 9 цифр!",
        booking_success: "✅ {name}, вы записаны к {doctor} на {time}!", booking_error: "❌ Ошибка. Попробуйте еще раз.", sending: "Отправка...",
        service_consultation: "Консультация и осмотр", service_extraction: "Удаление зуба", service_caries: "Лечение кариеса", service_pulpitis: "Лечение пульпита", service_cleaning: "Ультразвуковая чистка", service_whitening: "Отбеливание Zoom", service_crown: "Металлокерамика", service_zirconia: "Диоксид циркония", service_veneer: "Керамический винир", service_implant: "Дентальная имплантация", service_braces: "Брекет-система", service_gum: "Лечение десен", service_fissure: "Герметизация фиссур", service_xray: "3D снимок", service_nightguard: "Ночная каппа", service_wisdom: "Удаление зуба мудрости", service_aligners: "Исправление элайнерами",
        price_consultation: "500 сом", price_extraction: "от 599 сом", price_caries: "2000 сом", price_pulpitis: "3200 сом", price_cleaning: "2500 сом", price_whitening: "12000 сом", price_crown: "4500 сом", price_zirconia: "9500 сом", price_veneer: "15000 сом", price_implant: "22000 сом", price_braces: "25000 сом", price_gum: "1800 сом", price_fissure: "1200 сом", price_xray: "350 сом", price_nightguard: "3800 сом", price_wisdom: "от 4500 сом", price_aligners: "от 70000 сом",
        doctor_arapov: "Арапов Исламбек", doctor_arapov_role: "Главврач, Имплантолог", doctor_arapov_exp: "10 лет опыта", doctor_arapov_edu: "Ординатура по ЧЛХ. Специалист по системам Straumann и Osstem (Южная Корея).",
        doctor_ermatov: "Эрматов Бактыбек", doctor_ermatov_role: "Ортопед", doctor_ermatov_exp: "8 лет опыта", doctor_ermatov_edu: "Специализируется на безметалловых коронках E-Max и винирах CAD/CAM.",
        doctor_salieva: "Салиева Алина", doctor_salieva_role: "Эндодонтист", doctor_salieva_exp: "7 лет опыта", doctor_salieva_edu: "Эксперт реставрации фронтальной группы и лечению каналов под микроскопом.",
        doctor_kasymov: "Касымов Нурсултан", doctor_kasymov_role: "Ортодонт", doctor_kasymov_exp: "6 лет опыта", doctor_kasymov_edu: "Специалист по системам Damon и прозрачным элайнерам.",
        doctor_mamatova: "Маматова Назима", doctor_mamatova_role: "Детский стоматолог", doctor_mamatova_exp: "5 лет опыта", doctor_mamatova_edu: "Безболезненное лечение молочных зубов в игровой форме.",
        doctor_abdullaev: "Абдуллаев Рустам", doctor_abdullaev_role: "Гигиенист", doctor_abdullaev_exp: "5 лет опыта", doctor_abdullaev_edu: "Специализируется на профилактике и отбеливании Zoom 4.",
        footer_desc: "Клиника нового поколения в Кыргызстане.", footer_contacts: "Контакты", footer_address: "г. Ош, ул. Аскара Шакирова, 271", footer_hours: "График работы", footer_days: "Пн — Сб", footer_sunday: "Воскресенье — Выходной", footer_copyright: "Стоматология «Галерея Улыбок». Все права защищены."
    }
};
