const translations = {
    ru: {
        logo: 'Галерея <span class="logo__highlight">улыбок</span>',
        nav_about: 'О нас',
        nav_price: 'Прайс',
        nav_doctors: 'Врачи',
        nav_booking: 'Запись',
        nav_contacts: 'Контакты',
        
        hero_badge: 'Самая популярная стоматология Оша',
        hero_title: 'Красивая улыбка <br />начинается <span class="highlight">здесь</span>',
        hero_subtitle: 'Современная стоматология в центре Оша. Лечение, имплантация, брекеты и эстетика — всё в одной клинике.',
        feature1: '15 видов услуг',
        feature2: '6 опытных врачей',
        feature3: 'Современное оборудование',
        feature4: 'Средние цены',
        feature5: '5000+ довольных пациентов',
        btn_book: 'Записаться',
        btn_price: 'Прейскурант',
        reviews: 'отзывов',
        
        why_us: 'Почему мы',
        popular_title: 'Самая популярная клиника города',
        adv_1_title: '15 услуг',
        adv_1_desc: 'Полный спектр стоматологических услуг',
        adv_2_title: 'Средние цены',
        adv_2_desc: 'Доступная стоимость без потери качества',
        adv_3_title: '6 врачей',
        adv_3_desc: 'Опытные специалисты с высшим образованием',
        adv_4_title: 'Современное оборудование',
        adv_4_desc: 'Диагностика и лечение на мировом уровне',
        adv_5_title: 'Безболезненное лечение',
        adv_5_desc: 'Современная анестезия и комфорт',
        adv_6_title: 'Высокий рейтинг',
        adv_6_desc: '4.9 на основе 5000+ отзывов',
        
        about_label: 'О клинике',
        about_title: 'Почему выбирают <span class="highlight">Галерею улыбок</span>',
        about_text1: '«Галерея улыбок» — это современная стоматологическая клиника в самом центре Оша. Мы предлагаем полный спектр услуг: от профессиональной чистки до сложной имплантации и ортодонтии.',
        about_text2: 'Наши врачи — специалисты с многолетним опытом, регулярно повышающие квалификацию в ведущих клиниках Европы и Азии. Мы используем только проверенные материалы и оборудование последнего поколения.',
        about_text3: 'Главный принцип — индивидуальный подход к каждому пациенту и максимальный комфорт во время лечения.',
        stat_services: 'Услуг',
        stat_doctors: 'Врачей',
        stat_patients: 'Пациентов',
        stat_rating: 'Средняя оценка',
        exp_years: '10+ лет',
        exp_market: 'на рынке Кыргызстана',
        
        prices_label: 'Цены',
        prices_title: 'Прейскурант <span class="highlight">цен</span>',
        cat_diagnostic: 'Консультация и диагностика',
        cat_therapy: 'Терапия',
        cat_surgery: 'Хирургия и Имплантация',
        cat_hygiene: 'Гигиена и профилактика',
        
        price_consult: 'Консультация с составлением плана лечения',
        price_xray: 'Рентген 1 зуба',
        price_caries: 'Лечение кариеса (пломба световой полимеризации)',
        price_pulpitis: 'Лечение пульпита (1 канал)',
        price_extract: 'Удаление зуба простое',
        price_implant: 'Установка имплантата (Корея)',
        price_hygiene: 'Профессиональная гигиена (Air Flow + Ультразвук)',
        price_whitening: 'Отбеливание зубов (Zoom 4)',
        select: 'Выбрать',
        
        doctors_label: 'Врачи',
        doctors_title: 'Опытные <span class="highlight">специалисты</span>',
        doc1_name: 'Азиз Абдиев', doc1_spec: 'Главный врач, хирург-имплантолог', doc1_exp: '15 лет опыта',
        doc2_name: 'Айнура Абдылдаева', doc2_spec: 'Врач-терапевт, эндодонтист', doc2_exp: '12 лет опыта',
        doc3_name: 'Бекболот Маматов', doc3_spec: 'Ортодонт (Брекеты, элайнеры)', doc3_exp: '10 лет опыта',
        doc4_name: 'Гульмира Кыдырова', doc4_spec: 'Детский стоматолог', doc4_exp: '8 лет опыта',
        doc5_name: 'Жениш Осмонов', doc5_spec: 'Врач-ортопед (Виниры, коронки)', doc5_exp: '14 лет опыта',
        doc6_name: 'Чолпон Садыкова', doc6_spec: 'Пародонтолог (Лечение десен)', doc6_exp: '9 лет опыта',
        
        booking_label: 'Запись',
        booking_title: 'Запись <span class="highlight">на приём</span>',
        booking_desc: 'Заполните форму, и мы свяжемся с вами в ближайшее время для подтверждения записи.',
        label_lastname: 'Фамилия <span class="required">*</span>',
        label_firstname: 'Имя <span class="required">*</span>',
        label_phone: 'Телефон <span class="required">*</span>',
        label_doctor: 'Врач <span class="required">*</span>',
        label_service: 'Услуга <span class="required">*</span>',
        label_date: 'Дата <span class="required">*</span>',
        label_time: 'Время <span class="required">*</span>',
        label_comment: 'Комментарий',
        
        select_doctor: 'Выберите врача',
        doc1_opt: 'Азиз Абдиев — Хирург-имплантолог',
        doc2_opt: 'Айнура Абдылдаева — Терапевт',
        doc3_opt: 'Бекболот Маматов — Ортодонт',
        doc4_opt: 'Гульмира Кыдырова — Детский стоматолог',
        doc5_opt: 'Жениш Осмонов — Ортопед',
        doc6_opt: 'Чолпон Садыкова — Пародонтолог',
        
        select_service: 'Выберите услугу',
        select_time_first: 'Сначала выберите врача и дату',
        btn_book_submit: 'Отправить заявку',
        slogan: 'Красивая улыбка начинается здесь.'
    },
    uz: {
        logo: 'Galereya <span class="logo__highlight">tabassum</span>',
        nav_about: 'Biz haqimizda',
        nav_price: 'Narxlar',
        nav_doctors: 'Shifokorlar',
        nav_booking: 'Yozilish',
        nav_contacts: 'Aloqa',
        
        hero_badge: 'O\'shdagi eng mashhur stomatologiya',
        hero_title: 'Go\'zal tabassum <br />shu yerdan <span class="highlight">boshlanadi</span>',
        hero_subtitle: 'O\'sh markazidagi zamonaviy stomatologiya. Davolash, implantatsiya, breket va estetika — barchasi bitta klinikada.',
        feature1: '15 xil xizmat',
        feature2: '6 nafar tajribali shifokor',
        feature3: 'Zamonaviy uskunalar',
        feature4: 'Hamyonbop narxlar',
        feature5: '5000+ mamnun bemorlar',
        btn_book: 'Yozilish',
        btn_price: 'Narxlar ro\'yxati',
        reviews: 'sharhlar',
        
        why_us: 'Nima uchun biz',
        popular_title: 'Shahardagi eng mashhur klinika',
        adv_1_title: '15 ta xizmat',
        adv_1_desc: 'Stomatologik xizmatlarning to\'liq spektri',
        adv_2_title: 'Hamyonbop narxlar',
        adv_2_desc: 'Sifatni yo\'qotmagan holda maqbul narxlar',
        adv_3_title: '6 nafar shifokor',
        adv_3_desc: 'Oliy ma\'lumotli tajribali mutaxassislar',
        adv_4_title: 'Zamonaviy uskunalar',
        adv_4_desc: 'Jahon standartlari darajasida tashxis va davolash',
        adv_5_title: 'Og\'riqsiz davolash',
        adv_5_desc: 'Zamonaviy anesteziya va qulaylik',
        adv_6_title: 'Yuqori reyting',
        adv_6_desc: '5000+ sharhlar asosida 4.9 baho',
        
        about_label: 'Klinika haqida',
        about_title: 'Nega aynan <span class="highlight">Galereya tabassumni</span> tanlashadi',
        about_text1: '«Galereya tabassum» — bu O\'sh markazidagi zamonaviy stomatologiya klinikasi. Biz professional tozalashdan tortib, murakkab implantatsiya va ortodontiyagacha xizmatlarni taklif etamiz.',
        about_text2: 'Bizning shifokorlarimiz — ko\'p yillik tajribaga ega bo\'lib, Yevropa va Osiyoning yetakchi klinikalarida muntazam malaka oshiradilar. Biz faqat tekshirilgan materiallar va so\'nggi avlod uskunalaridan foydalanamiz.',
        about_text3: 'Asosiy tamoyilimiz — har bir bemorga individual yondashuv va davolanish vaqtida maksimal qulaylikni ta\'minlash.',
        stat_services: 'Xizmatlar',
        stat_doctors: 'Shifokorlar',
        stat_patients: 'Bemorlar',
        stat_rating: 'O\'rtacha baho',
        exp_years: '10+ yil',
        exp_market: 'Qirg\'iziston bozorida',
        
        prices_label: 'Narxlar',
        prices_title: 'Narxlar <span class="highlight">ro\'yxati</span>',
        cat_diagnostic: 'Konsultatsiya va diagnostika',
        cat_therapy: 'Terapiya',
        cat_surgery: 'Xirurgiya va Implantatsiya',
        cat_hygiene: 'Gigiyena va profilaktika',
        
        price_consult: 'Davolash rejasini tuzish va konsultatsiya',
        price_xray: '1 ta tish rentgeni',
        price_caries: 'Kariyesni davolash (yorug\'lik plombasi)',
        price_pulpitis: 'Pulpitni davolash (1 kanal)',
        price_extract: 'Tishni oddiy yulish',
        price_implant: 'Implantat o\'rnatish (Koreya)',
        price_hygiene: 'Professional gigiyena (Air Flow + Ultrazvuk)',
        price_whitening: 'Tishlarni oqartirish (Zoom 4)',
        select: 'Tanlash',
        
        doctors_label: 'Shifokorlar',
        doctors_title: 'Tajribali <span class="highlight">mutaxassislar</span>',
        doc1_name: 'Aziz Abdiyev', doc1_spec: 'Bosh shifokor, jarroh-implantolog', doc1_exp: '15 yillik tajriba',
        doc2_name: 'Aynura Abdildayeva', doc2_spec: 'Terapevt-shifokor, endodontist', doc2_exp: '12 yillik tajriba',
        doc3_name: 'Bekbolot Mamatov', doc3_spec: 'Ortodont (Breketlar, elaynerlar)', doc3_exp: '10 yillik tajriba',
        doc4_name: 'Gulmira Kydyrova', doc4_spec: 'Bolalar stomatologi', doc4_exp: '8 yillik tajriba',
        doc5_name: 'Jenish Osmonov', doc5_spec: 'Ortoped-shifokor (Vinirlar, tojlar)', doc5_exp: '14 yillik tajriba',
        doc6_name: 'Cholpon Sadikova', doc6_spec: 'Parodontolog (Miklarni davolash)', doc6_exp: '9 yillik tajriba',
        
        booking_label: 'Yozilish',
        booking_title: 'Qabulga <span class="highlight">yozilish</span>',
        booking_desc: 'Shaklni to\'ldiring, va biz yozuvni tasdiqlash uchun tez orada siz bilan bog\'lanamiz.',
        label_lastname: 'Familiya <span class="required">*</span>',
        label_firstname: 'Ism <span class="required">*</span>',
        label_phone: 'Telefon <span class="required">*</span>',
        label_doctor: 'Shifokor <span class="required">*</span>',
        label_service: 'Xizmat <span class="required">*</span>',
        label_date: 'Sana <span class="required">*</span>',
        label_time: 'Vaqt <span class="required">*</span>',
        label_comment: 'Izoh',
        
        select_doctor: 'Shifokorni tanlang',
        doc1_opt: 'Aziz Abdiyev — Jarroh-implantolog',
        doc2_opt: 'Aynura Abdildayeva — Terapevt',
        doc3_opt: 'Bekbolot Mamatov — Ortodont',
        doc4_opt: 'Gulmira Kydyrova — Bolalar stomatologi',
        doc5_opt: 'Jenish Osmonov — Ortoped',
        doc6_opt: 'Cholpon Sadikova — Parodontolog',
        
        select_service: 'Xizmatni tanlang',
        select_time_first: 'Avval shifokor va sanani tanlang',
        btn_book_submit: 'Ariza yuborish',
        slogan: 'Go\'zal tabassum shu yerdan boshlanadi.'
    },
    ky: {
        logo: 'Жылмаюу <span class="logo__highlight">галереясы</span>',
        nav_about: 'Биз жөнүндө',
        nav_price: 'Баалар',
        nav_doctors: 'Дарыгерлер',
        nav_booking: 'Жазылуу',
        nav_contacts: 'Байланыш',
        
        hero_badge: 'Оштогу эң популярдуу стоматология',
        hero_title: 'Кооз жылмаюу <br />ушул жерден <span class="highlight">башталат</span>',
        hero_subtitle: 'Оштун борборундагы заманбап стоматология. Дарылоо, имплантация, брекеттер жана эстетика — баары бир клиникада.',
        feature1: '15 түрдүү кызмат',
        feature2: '6 тажрыйбалуу дарыгер',
        feature3: 'Заманбап жабдуулар',
        feature4: 'Жеткиликтүү баалар',
        feature5: '5000+ ыраазы болгон бейтаптар',
        btn_book: 'Жазылуу',
        btn_price: 'Баалар тизмеси',
        reviews: 'пикирлер',
        
        why_us: 'Эмнеге биз',
        popular_title: 'Шаардагы эң популярдуу клиника',
        adv_1_title: '15 кызмат',
        adv_1_desc: 'Стоматологиялык кызматтардын толук спектри',
        adv_2_title: 'Жеткиликтүү баалар',
        adv_2_desc: 'Сапатты жоготпостон ылайыктуу баалар',
        adv_3_title: '6 дарыгер',
        adv_3_desc: 'Жогорку билимдүү тажрыйбалуу адистер',
        adv_4_title: 'Заманбап жабдуулар',
        adv_4_desc: 'Дүйнөлүк деңгээлдеги диагностика жана дарылоо',
        adv_5_title: 'Оорутпаган дарылоо',
        adv_5_desc: 'Заманбап анестезия жана ыңгайлуулук',
        adv_6_title: 'Жогорку рейтинг',
        adv_6_desc: '5000+ пикирлердин негизинде 4.9 баа',
        
        about_label: 'Клиника жөнүндө',
        about_title: 'Эмнеге <span class="highlight">Жылмаюу галереясын</span> тандашат',
        about_text1: '«Жылмаюу галереясы» — бул Оштун чок ортосундагы заманбап стоматологиялык клиника. Биз кесиптик тазалоодон баштап, татаал имплантацияга чейин кызматтарды сунуштайбыз.',
        about_text2: 'Биздин дарыгерлер — Европа жана Азиянын алдыңкы клиникаларында дайыма квалификациясын жогорулаткан көп жылдык тажрыйбасы бар адистер.',
        about_text3: 'Негизги принцип — ар бир бейтапка жеке мамиле жасоо жана дарылоо учурунда максималдуу ыңгайлуулукту камсыз кылуу.',
        stat_services: 'Кызматтар',
        stat_doctors: 'Дарыгерлер',
        stat_patients: 'Бейтаптар',
        stat_rating: 'Орточо баа',
        exp_years: '10+ жыл',
        exp_market: 'Кыргызстандын рыногунда',
        
        prices_label: 'Баалар',
        prices_title: 'Баалар <span class="highlight">тизмеси</span>',
        cat_diagnostic: 'Консультация жана диагностика',
        cat_therapy: 'Терапия',
        cat_surgery: 'Хирургия жана Имплантация',
        cat_hygiene: 'Гигиена жана профилактика',
        
        price_consult: 'Дарылоо планын түзүү менен консультация',
        price_xray: '1 тиштин рентгени',
        price_caries: 'Кариести дарылоо (жарык пломбасы)',
        price_pulpitis: 'Пульпити дарылоо (1 канал)',
        price_extract: 'Тишти жөнөкөй жулуу',
        price_implant: 'Имплантат орнотуу (Корея)',
        price_hygiene: 'Кесиптик гигиена (Air Flow + УЗИ)',
        price_whitening: 'Тишти агартуу (Zoom 4)',
        select: 'Тандоо',
        
        doctors_label: 'Дарыгерлер',
        doctors_title: 'Тажрыйбалуу <span class="highlight">адистер</span>',
        doc1_name: 'Азиз Абдиев', doc1_spec: 'Башкы дарыгер, хирург-имплантолог', doc1_exp: '15 жылдык тажрыйба',
        doc2_name: 'Айнура Абдылдаева', doc2_spec: 'Терапевт-дарыгер, эндодонтист', doc2_exp: '12 жылдык тажрыйба',
        doc3_name: 'Бекболот Маматов', doc3_spec: 'Ортодонт (Брекеттер, элайнерлер)', doc3_exp: '10 жылдык тажрыйба',
        doc4_name: 'Гульмира Кыдырова', doc4_spec: 'Балдар стоматологу', doc4_exp: '8 жылдык тажрыйба',
        doc5_name: 'Жениш Осмонов', doc5_spec: 'Ортопед-дарыгер (Винирлер, таажылар)', doc5_exp: '14 жылдык тажрыйба',
        doc6_name: 'Чолпон Садыкова', doc6_spec: 'Пародонтолог (Мүлктү дарылоо)', doc6_exp: '9 жылдык тажрыйба',
        
        booking_label: 'Жазылуу',
        booking_title: 'Кабыл алууга <span class="highlight">жазылуу</span>',
        booking_desc: 'Форманы толтуруңуз, биз жазылууну ырастоо үчүн жакында сиз менен байланышабыз.',
        label_lastname: 'Фамилия <span class="required">*</span>',
        label_firstname: 'Аты <span class="required">*</span>',
        label_phone: 'Телефон <span class="required">*</span>',
        label_doctor: 'Дарыгер <span class="required">*</span>',
        label_service: 'Кызмат <span class="required">*</span>',
        label_date: 'Күнү <span class="required">*</span>',
        label_time: 'Убактысы <span class="required">*</span>',
        label_comment: 'Комментарий',
        
        select_doctor: 'Дарыгерди тандаңыз',
        doc1_opt: 'Азиз Абдиев — Хирург-имплантолог',
        doc2_opt: 'Айнура Абдылдаева — Терапевт',
        doc3_opt: 'Бекболот Маматов — Ортодонт',
        doc4_opt: 'Гульмира Кыдырова — Балдар стоматологу',
        doc5_opt: 'Жениш Осмонов — Ортопед',
        doc6_opt: 'Чолпон Садыкова — Пародонтолог',
        
        select_service: 'Кызматты тандаңыз',
        select_time_first: 'Алгач дарыгерди жана күндү тандаңыз',
        btn_book_submit: 'Табыштама жөнөтүү',
        slogan: 'Кооз жылмаюу ушул жерден башталат.'
    },
    en: {
        logo: 'Smile <span class="logo__highlight">Gallery</span>',
        nav_about: 'About Us',
        nav_price: 'Prices',
        nav_doctors: 'Doctors',
        nav_booking: 'Book',
        nav_contacts: 'Contacts',
        
        hero_badge: 'The Most Popular Dentistry in Osh',
        hero_title: 'A beautiful smile <br />starts <span class="highlight">here</span>',
        hero_subtitle: 'Modern dentistry in the center of Osh. Treatment, implantation, braces, and aesthetics — all in one clinic.',
        feature1: '15 types of services',
        feature2: '6 experienced doctors',
        feature3: 'Modern equipment',
        feature4: 'Affordable prices',
        feature5: '5000+ happy patients',
        btn_book: 'Book an Appointment',
        btn_price: 'Price List',
        reviews: 'reviews',
        
        why_us: 'Why Us',
        popular_title: 'The Most Popular Clinic in the City',
        adv_1_title: '15 Services',
        adv_1_desc: 'Full range of dental services',
        adv_2_title: 'Affordable Prices',
        adv_2_desc: 'Reasonable cost without compromising quality',
        adv_3_title: '6 Doctors',
        adv_3_desc: 'Experienced specialists with higher education',
        adv_4_title: 'Modern Equipment',
        adv_4_desc: 'World-class diagnostics and treatment',
        adv_5_title: 'Painless Treatment',
        adv_5_desc: 'Modern anesthesia and comfort',
        adv_6_title: 'High Rating',
        adv_6_desc: '4.9 based on 5000+ reviews',
        
        about_label: 'About Clinic',
        about_title: 'Why people choose <span class="highlight">Smile Gallery</span>',
        about_text1: '"Smile Gallery" is a modern dental clinic right in the center of Osh. We offer a full range of services: from professional cleaning to complex implantation and orthodontics.',
        about_text2: 'Our doctors are specialists with many years of experience, regularly improving their qualifications in leading clinics in Europe and Asia.',
        about_text3: 'The main principle is an individual approach to each patient and maximum comfort during treatment.',
        stat_services: 'Services',
        stat_doctors: 'Doctors',
        stat_patients: 'Patients',
        stat_rating: 'Average Rating',
        exp_years: '10+ years',
        exp_market: 'in the Kyrgyzstan market',
        
        prices_label: 'Prices',
        prices_title: 'Price <span class="highlight">List</span>',
        cat_diagnostic: 'Consultation and Diagnostics',
        cat_therapy: 'Therapy',
        cat_surgery: 'Surgery and Implantation',
        cat_hygiene: 'Hygiene and Prevention',
        
        price_consult: 'Consultation with a treatment plan',
        price_xray: 'X-ray of 1 tooth',
        price_caries: 'Caries treatment (light-curing filling)',
        price_pulpitis: 'Pulpitis treatment (1 canal)',
        price_extract: 'Simple tooth extraction',
        price_implant: 'Implant installation (Korea)',
        price_hygiene: 'Professional hygiene (Air Flow + Ultrasound)',
        price_whitening: 'Teeth whitening (Zoom 4)',
        select: 'Select',
        
        doctors_label: 'Doctors',
        doctors_title: 'Experienced <span class="highlight">Specialists</span>',
        doc1_name: 'Aziz Abdiev', doc1_spec: 'Head Doctor, Surgeon-Implantologist', doc1_exp: '15 years of experience',
        doc2_name: 'Ainura Abdyldaeva', doc2_spec: 'Therapist, Endodontist', doc2_exp: '12 years of experience',
        doc3_name: 'Bekbolot Mamatov', doc3_spec: 'Orthodontist (Braces, aligners)', doc3_exp: '10 years of experience',
        doc4_name: 'Gulmira Kydyrova', doc4_spec: 'Pediatric Dentist', doc4_exp: '8 years of experience',
        doc5_name: 'Zhenish Osmonov', doc5_spec: 'Orthopedist (Veneers, crowns)', doc5_exp: '14 years of experience',
        doc6_name: 'Cholpon Sadykova', doc6_spec: 'Periodontist (Gum treatment)', doc6_exp: '9 years of experience',
        
        booking_label: 'Booking',
        booking_title: 'Book an <span class="highlight">Appointment</span>',
        booking_desc: 'Fill out the form, and we will contact you shortly to confirm your appointment.',
        label_lastname: 'Last Name <span class="required">*</span>',
        label_firstname: 'First Name <span class="required">*</span>',
        label_phone: 'Phone <span class="required">*</span>',
        label_doctor: 'Doctor <span class="required">*</span>',
        label_service: 'Service <span class="required">*</span>',
        label_date: 'Date <span class="required">*</span>',
        label_time: 'Time <span class="required">*</span>',
        label_comment: 'Comment',
        
        select_doctor: 'Select a doctor',
        doc1_opt: 'Aziz Abdiev — Surgeon-Implantologist',
        doc2_opt: 'Ainura Abdyldaeva — Therapist',
        doc3_opt: 'Bekbolot Mamatov — Orthodontist',
        doc4_opt: 'Gulmira Kydyrova — Pediatric Dentist',
        doc5_opt: 'Zhenish Osmonov — Orthopedist',
        doc6_opt: 'Cholpon Sadykova — Periodontist',
        
        select_service: 'Select a service',
        select_time_first: 'Select a doctor and date first',
        btn_book_submit: 'Submit Request',
        slogan: 'A beautiful smile starts here.'
    }
};

function applyLanguage(lang) {
    document.querySelectorAll('[data-lang]').forEach(el => {
        const key = el.getAttribute('data-lang');
        if (translations[lang] && translations[lang][key] !== undefined) {
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') {
                el.placeholder = translations[lang][key];
            } else if (el.tagName === 'OPTION') {
                el.innerHTML = translations[lang][key]; 
            } else {
                el.innerHTML = translations[lang][key];
            }
        }
    });
    document.getElementById('langSelect').value = lang;
    localStorage.setItem('lang', lang);
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('lang') || 'ru';
    applyLanguage(savedLang);
    document.getElementById('langSelect').addEventListener('change', function() {
        applyLanguage(this.value);
    });
});
